### ISSUE TITLE
Theme isn't working with the bibtex plugin

### ISSUE THREAD

**Issue by Medienbecken** [nsteiner/kdoc#1]
The Bibtex plugin (https://www.mundhenk.org/blog/kirby-bibtex) seems not to woork with this template because off jquerry issues. I'll report this as an issue at the plugins repo as well.
I'd be verry happy if the problem could be fixed.

**Comment by nsteiner** [comment]
@Medienbecken interesting, I haven't seen this plugin before. Looks like [it injects](https://github.com/PhilippMundhenk/Kirby-BibTeX/blob/master/site/tags/bibtex.php) an older version of jQuery, as well as another library which requires it. I suppose the default Kirby starter kit doesn't include jQuery, so it's not an issue there.

I tried using the older version of jQuery with the two libraries I have included (code highlighting, and menu accordion), but unfortunately they were written in a way that requires a more up to date version of jQuery.

I'm definitely open to modifying the KDoc JS so it's compatible with this plugin, but I haven't found a sensible way to do that yet.

**Comment by nsteiner** [comment]
On second review, it looks like the code highlighting script could be used without jQuery, the accordion menu script is the only part that requires it. It would be a good exercise to re-code the accordion menu to use plain Javascript. Once that's done, jQuery can be removed completely, which would make the Bibtex plugin compatible with KDoc.

**Comment by Medienbecken** [comment]
I'm not good at writing JS, but that sounds nice. Are you going to do the changes?

**Comment by nsteiner** [comment]
@Medienbecken yes, I think it would be an improvement overall - it's on my to-do list.

**Comment by nsteiner** [comment]
@Medienbecken I've updated the scripts to no longer use jQuery, which should hopefully allow Bibtex to work. Do you mind pulling the latest and giving it another try?

**Comment by Medienbecken** [comment]
@nsteiner I'm quite busy at the moment but I'm going to test it as soon as posible.

**Comment by nsteiner** [comment]
I believe this is probably working, since jQuery is taken out of the equation.

**Comment by Medienbecken** [comment]
thats why the developer already closed the tread (-;

**Comment by nsteiner** [comment]
@Medienbecken I'm very confused. But if it's working for you - great! Cheers.
