### ISSUE TITLE
Accordion bug when multiple pages have subpages

### ISSUE THREAD

**Issue by larshaendler** [nsteiner/kdoc#4]
When I add new subpages to any of the top level hierarchy pages the "+" button accordion does not work properly. It will always open the first accordion and will ignore all following accordions. 

Here is a short screencast: http://www.screencast.com/t/3Hawdk8AKIks

I am not a JavaScript crack but this line does only take the very first occurance of the button having the expand-subnav class: 
`var button = el.querySelectorAll('.expand-subnav')[0];`

**Comment by nsteiner** [comment]
Thanks @larshaendler very helpful - will fix.

**Comment by nsteiner** [comment]
This issue is now fixed, the latest commit includes a Kirby upgrade, but if you just want this fix, the only file that needs to be updated is here:
https://github.com/nsteiner/kdoc/blob/master/assets/js/libs/accordion-plain.js

Thanks @larshaendler for reporting this.
