### ISSUE TITLE
Implementing search functionality

### ISSUE THREAD

**Issue by wout** [nsteiner/kdoc#8]
Hi,

I love this theme and would like to use it as a documentation tool for various projects I'm working on, including my own [svg.js](https://github.com/svgdotjs/svg.js). The only thing I am missing is a search. Is there any way to implement this easily? Or would I need to built that myself?

**Comment by nsteiner** [comment]
Thanks for the kind words! 
If you're publishing with the full Kirby install, adding search should be relatively painless. Here's a cookbook recipe for it:
https://getkirby.com/docs/cookbook/search

**Comment by nsteiner** [comment]
Oops I hit the comment button early.
I agree that search should be added. Feel free to pull request if you get to it before I do.
I haven't sorted out what to do about search for those of us that export to static. I suppose a JS solution would be needed for that.

**Comment by wout** [comment]
I looked at the cookbook solution and that would be my next step. But it would have been nice to have something ready to use (like many of us I don't have a lot of spare time :).

You're right about the static version. A JS implementation would be the best way to go. Although, that would require a static search index because we're dealing with separate pages. Not undoable but requires some work/time. I'll have a look into it.

Thanks anyway!

**Comment by nsteiner** [comment]
You're right. I didn't mean to imply that you should have to do it. I'll put together the php version tomorrow and update here when it's ready.
The static one is important to me, but may take a while longer to figure out.

**Comment by wout** [comment]
Great! Looking forward to it!

**Comment by nsteiner** [comment]
Ok done from the road. Now I just need a laptop internet connection to upload it (tonight).

Sneak peek:
![screen shot 2016-11-26 at 1 28 41 pm](https://cloud.githubusercontent.com/assets/111835/20642440/e06847ce-b3dc-11e6-9011-4780a4e4aef2.png)

**Comment by wout** [comment]
That's quick ;)
Looks great.

Will it be possible to place it anywhere?
Like, say in the header ont the top right for example?

**Comment by nsteiner** [comment]
Yes absolutely. It's a simple form that can be placed anywhere.

**Comment by nsteiner** [comment]
Ok [the new code is committed](https://github.com/nsteiner/kdoc/commit/4dcad8579f480a39e2fbdb156f2f8d39c307f719) and available. I put the search form in the header like you suggested but it's quite portable.

![screen shot 2016-11-26 at 9 27 41 pm](https://cloud.githubusercontent.com/assets/111835/20645090/32bae9b8-b41f-11e6-9f52-dd9cf53cc6df.png)

Thanks for the suggestion! I'm going to close this issue and make a new one for the version which works with static sites. Please let me know if you run into any issues with it.

**Comment by wout** [comment]
Excellent! Many thanks for your quick intervention.
